### ISSUE TITLE
Controller::$layout is deprecated

### ISSUE THREAD

**Issue by web-ap** [Xety/Xeta#173]
Hi!
I have an issue when I'm trying to open the admin dashbord or the forum. 
I have this message : Controller::$layout is deprecated. Use $this->viewBuilder()->layout() instead.
But I can't find the revelant file and function. Can you help me? Thanks!

PS: I didn't add any code lines. It's a fresh install.

**Comment by Xety** [comment]
Hello,

Weird for a fresh install, because this deprecation is in Cake 3.1, and Xeta use a version "3.0.X" (~3.0).

Anyways, there you go :
https://github.com/Xety/Xeta/blob/master/src/Controller/AppController.php#L167-L171
https://github.com/Xety/Xeta/blob/master/src/Controller/ConversationsController.php#L550
https://github.com/Xety/Xeta/blob/master/src/Controller/Forum/PostsController.php#L492

To replace (exemple):
`$this->layout = 'admin'` => `$this->viewBuilder()->layout('admin')`
`$this->layout = false` => `$this->viewBuilder()->layout(false)`

**Comment by antograssiot** [comment]
@Xety ~3.0 will fetch 3.1...

**Comment by Xety** [comment]
Ah ? I tried a composer update on a app with ~3.0 when the 3.1 has been released, and it didn't update.

**Comment by web-ap** [comment]
thanks a lot, it works! 
I don't know how I missed it in docs... Anyway, great work!
